name: scm
description: Sistema Central de MensajerÃ­a.

publish_to: "none"

# Para cambiar la version completamente, Archivos Afectados
# lib\src\vars\globals.dart | Line: 8
# android\app\build.gradle    | Line: 21
# Este archivo
version: 2.0.0+0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  bitsdojo_window: ^0.1.5
  cron: ^0.5.0
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  glass_kit: ^2.0.1
  google_fonts: ^3.0.1
  http: ^0.13.5
  network_info_plus: ^3.0.1
  path: ^1.8.2
  path_provider: ^2.0.11
  provider: ^6.0.4
  puppeteer: ^2.17.0
  web_socket_channel: ^2.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/logo_dark.png
    - assets/logo_1024.png
